apiVersion: apps/v1
kind: Deployment
metadata:
  name: homework-dep
  namespace: homework
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homework
  template:
    metadata:
      labels:
        app: homework
    spec:
      containers:
      - name: homework
        image: noamsegevgabay/home_work_noam:11
        ports:
        - containerPort: 8080










