apiVersion: v1
kind: Service
metadata:
  name: homework-svc
  namespace: homework
spec:
  selector:
    app: homework
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
#